#!/usr/bin/env node
/**
 * my-flow build: renders the single-source content under src/ into the two
 * tool surfaces (Claude Code plugin + Codex CLI files).
 *
 *   node scripts/build.mjs          write outputs
 *   node scripts/build.mjs --check  exit 1 if any output is out of date
 *
 * Source conventions (see README):
 *   {{ARGS}}                       -> $ARGUMENTS (Claude) / {{ARGUMENTS}} (Codex)
 *   {{CALL:name}}                  -> /my-flow:name (Claude) / $my-flow-name (Codex)
 *   <!-- MY-FLOW:CLAUDE --> ... <!-- /MY-FLOW:CLAUDE -->   kept only for Claude
 *   <!-- MY-FLOW:CODEX -->  ... <!-- /MY-FLOW:CODEX -->    kept only for Codex
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const CHECK = process.argv.includes('--check');
const manifest = JSON.parse(readFileSync(join(ROOT, 'manifest.json'), 'utf8'));
const VERSION = manifest.version;
const PLUGIN = manifest.pluginName;
const CODEX_PREFIX = manifest.codexSkillPrefix;

// ---------- helpers ----------
function parseFrontmatter(text) {
  const m = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?([\s\S]*)$/.exec(text);
  if (!m) return { meta: {}, body: text };
  const meta = {};
  for (const line of m[1].split(/\r?\n/)) {
    const kv = /^([A-Za-z0-9_-]+):\s*(.*)$/.exec(line);
    if (!kv) continue;
    let v = kv[2].trim();
    if ((v.startsWith('"') && v.endsWith('"')) || (v.startsWith("'") && v.endsWith("'"))) v = v.slice(1, -1);
    meta[kv[1]] = v;
  }
  return { meta, body: m[2] };
}

function yamlValue(v) {
  if (typeof v === 'boolean' || typeof v === 'number') return String(v);
  const s = String(v);
  return /[:#\[\]{}<>&*!|'"%@`,?]|^\s|\s$/.test(s) ? JSON.stringify(s) : s;
}

function frontmatter(obj) {
  const lines = ['---'];
  for (const [k, v] of Object.entries(obj)) {
    if (v === undefined || v === null || v === '') continue;
    lines.push(`${k}: ${yamlValue(v)}`);
  }
  lines.push('---');
  return lines.join('\n') + '\n';
}

function renderBody(body, tool) {
  let out = body.replace(/\r\n/g, '\n');
  out = out.replace(/<!-- MY-FLOW:(CLAUDE|CODEX) -->\n?([\s\S]*?)<!-- \/MY-FLOW:\1 -->\n?/g, (_, which, inner) =>
    which.toLowerCase() === tool ? inner : ''
  );
  out = out.replace(/\{\{ARGS\}\}/g, tool === 'claude' ? '$ARGUMENTS' : '{{ARGUMENTS}}');
  out = out.replace(/\{\{CALL:([a-z-]+)\}\}/g, (_, n) => (tool === 'claude' ? `/${PLUGIN}:${n}` : `$${CODEX_PREFIX}${n}`));
  out = out.replace(/\{\{VERSION\}\}/g, VERSION);
  out = out.replace(/\n{3,}/g, '\n\n');
  return out.replace(/^\n+/, '').trimEnd() + '\n';
}

const outputs = new Map(); // relPath -> content
function emit(rel, content) {
  outputs.set(rel.replace(/\\/g, '/'), content);
}

// ---------- skills ----------
for (const [name, cfg] of Object.entries(manifest.skills)) {
  const src = readFileSync(join(ROOT, 'src', 'skills', `${name}.md`), 'utf8');
  const { meta, body } = parseFrontmatter(src);
  if (!meta.description) throw new Error(`src/skills/${name}.md: missing description`);

  const claudeMeta = {
    name,
    description: meta.description,
    'argument-hint': meta['argument-hint'],
    ...(cfg.claude ?? {}),
  };
  emit(`skills/${name}/SKILL.md`, frontmatter(claudeMeta) + '\n' + renderBody(body, 'claude'));

  const codexMeta = {
    name: `${CODEX_PREFIX}${name}`,
    description: meta.description,
    'argument-hint': meta['argument-hint'],
    ...(cfg.codex ?? {}),
  };
  emit(`codex/skills/${CODEX_PREFIX}${name}/SKILL.md`, frontmatter(codexMeta) + '\n' + renderBody(body, 'codex'));
}

// ---------- agents ----------
const TRIPLE_QUOTE = "'".repeat(3);
function tomlLiteral(s) {
  if (s.includes(TRIPLE_QUOTE)) throw new Error('agent body must not contain a TOML literal-string terminator');
  return `${TRIPLE_QUOTE}\n${s}${TRIPLE_QUOTE}`;
}
for (const [name, cfg] of Object.entries(manifest.agents)) {
  const src = readFileSync(join(ROOT, 'src', 'agents', `${name}.md`), 'utf8');
  const { meta, body } = parseFrontmatter(src);
  if (!meta.description) throw new Error(`src/agents/${name}.md: missing description`);

  const claudeMeta = {
    name,
    description: meta.description,
    model: cfg.claude?.model,
    disallowedTools: meta.disallowedTools,
  };
  emit(`agents/${name}.md`, frontmatter(claudeMeta) + '\n' + renderBody(body, 'claude'));

  const c = cfg.codex ?? {};
  const toml = [
    `# my-flow agent: ${name} (generated by scripts/build.mjs - edit src/agents/${name}.md instead)`,
    `name = ${JSON.stringify(name)}`,
    `description = ${JSON.stringify(meta.description)}`,
    c.model ? `model = ${JSON.stringify(c.model)}` : null,
    c.model_reasoning_effort ? `model_reasoning_effort = ${JSON.stringify(c.model_reasoning_effort)}` : null,
    `developer_instructions = ${tomlLiteral(renderBody(body, 'codex'))}`,
    '',
  ].filter((l) => l !== null).join('\n');
  emit(`codex/agents/${name}.toml`, toml);
}

// ---------- core document ----------
{
  const core = readFileSync(join(ROOT, 'src', 'core', 'core.md'), 'utf8');
  const wrap = (tool) =>
    `<!-- MY-FLOW:START v${VERSION} -->\n` +
    `<!-- Generated by my-flow (scripts/build.mjs). Edit src/core/core.md, not this block. -->\n` +
    renderBody(core, tool) +
    `<!-- MY-FLOW:END -->\n`;
  emit('claude/CLAUDE.block.md', wrap('claude'));
  emit('codex/AGENTS.block.md', wrap('codex'));
}

// ---------- plugin manifest ----------
{
  const pkg = JSON.parse(readFileSync(join(ROOT, 'package.json'), 'utf8'));
  const plugin = {
    name: PLUGIN,
    version: VERSION,
    description: pkg.description,
    author: { name: 'Qither' },
    repository: 'https://github.com/Qither/my-flow',
    license: 'MIT',
    keywords: ['claude-code', 'codex', 'workflow', 'openspec', 'plugin'],
    skills: Object.keys(manifest.skills).map((n) => `./skills/${n}/`),
    agents: Object.keys(manifest.agents).map((n) => `./agents/${n}.md`),
    hooks: './hooks/hooks.json',
  };
  emit('.claude-plugin/plugin.json', JSON.stringify(plugin, null, 2) + '\n');
}

// ---------- codex hooks template ----------
{
  const cmd = (script) =>
    `powershell.exe -NoProfile -ExecutionPolicy Bypass -File "{{SHIM}}" -Script "{{ROOT}}/hooks/${script}"`;
  const hooks = {
    hooks: {
      SessionStart: [
        { matcher: 'startup|resume|clear', hooks: [{ type: 'command', command: cmd('session-context.mjs'), timeout: 10 }] },
      ],
      Stop: [{ hooks: [{ type: 'command', command: cmd('completion-guard.mjs'), timeout: 30 }] }],
    },
  };
  emit('codex/hooks.template.json', JSON.stringify(hooks, null, 2) + '\n');
}

// ---------- write / check ----------
let changed = 0;
for (const [rel, content] of outputs) {
  const abs = join(ROOT, rel);
  const current = existsSync(abs) ? readFileSync(abs, 'utf8').replace(/\r\n/g, '\n') : null;
  if (current === content) continue;
  changed++;
  if (CHECK) {
    console.error(`out of date: ${rel}`);
  } else {
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content, 'utf8');
    console.log(`wrote ${rel}`);
  }
}

// prune stale generated skill/agent entries
if (!CHECK) {
  const pruneDir = (dir, keep) => {
    const abs = join(ROOT, dir);
    if (!existsSync(abs)) return;
    for (const entry of readdirSync(abs)) {
      if (!keep.has(entry)) {
        rmSync(join(abs, entry), { recursive: true, force: true });
        console.log(`removed stale ${dir}/${entry}`);
      }
    }
  };
  pruneDir('skills', new Set(Object.keys(manifest.skills)));
  pruneDir('codex/skills', new Set(Object.keys(manifest.skills).map((n) => CODEX_PREFIX + n)));
  pruneDir('agents', new Set(Object.keys(manifest.agents).map((n) => `${n}.md`)));
  pruneDir('codex/agents', new Set(Object.keys(manifest.agents).map((n) => `${n}.toml`)));
}

if (CHECK) {
  if (changed) {
    console.error(`${changed} generated file(s) out of date. Run: node scripts/build.mjs`);
    process.exit(1);
  }
  console.log('generated files are up to date');
} else {
  console.log(changed ? `build complete (${changed} file(s) written)` : 'build complete (no changes)');
}
